import React from 'react';
import { cn } from '../../lib/utils';
import { Brain, Info } from 'lucide-react';

interface AIAdvisoryLabelProps {
  className?: string;
  showIcon?: boolean;
  size?: 'sm' | 'md' | 'lg';
  context?: 'inline' | 'banner';
}

export const AIAdvisoryLabel: React.FC<AIAdvisoryLabelProps> = ({
  className,
  showIcon = true,
  size = 'md',
  context = 'inline',
}) => {
  const sizeClasses = {
    sm: 'text-xs px-2 py-0.5',
    md: 'text-sm px-2.5 py-1',
    lg: 'text-base px-3 py-1.5',
  };
  
  const iconSizes = {
    sm: 'w-3 h-3',
    md: 'w-4 h-4',
    lg: 'w-5 h-5',
  };
  
  if (context === 'banner') {
    return (
      <div
        className={cn(
          'flex items-start gap-3 p-4 rounded-lg border bg-advisory-50 border-advisory-200',
          className
        )}
      >
        <Brain className={cn('text-advisory-600 flex-shrink-0 mt-0.5', iconSizes[size])} />
        <div>
          <p className="font-medium text-advisory-800">AI Advisory Output</p>
          <p className="text-advisory-600 text-sm mt-1">
            The following findings are generated by artificial intelligence and are provided 
            for advisory purposes only. AI output does not constitute legal authority. 
            Final decisions are made by human authority.
          </p>
        </div>
      </div>
    );
  }
  
  return (
    <span
      className={cn(
        'inline-flex items-center gap-1.5 font-medium rounded-full bg-advisory-100 text-advisory-700',
        sizeClasses[size],
        className
      )}
    >
      {showIcon && <Brain className={iconSizes[size]} />}
      <span>AI Advisory</span>
      <Info className={cn('text-advisory-500', iconSizes[size])} />
    </span>
  );
};
