module.exports = {
  LEGAL_MODE: "compliant",
  AUTHORITY_PROVIDER: "human_commissioned",
  ALLOW_AUTONOMOUS_EXECUTION: false,
  REQUIRE_HUMAN_FINAL_SIGNOFF: true,
  REQUIRE_HUMAN_CEREMONY: true,
  REQUIRE_JURISDICTION_POLICY_ENFORCEMENT: true,
  ENABLE_SHADOW_AUTONOMOUS_BENCHMARKING: false,
  STRICT_EVIDENCE_MODE: true,
  PROTOCOL_PUBLICATION_MODE: "disabled",
  EVIDENCE_OUTPUT_DIR: "overlay/evidence/exports",
};
